export enum Roles {
    Branch = 'branch',
    Assets = 'assets',
    Appointments = 'appointments',
    Staff = 'staff',
    Client = 'client',
    Vendor = 'vendor',
    SubDealer = 'subdealer',
    Hiring = 'hiring',
    Bank = 'bank',
    Product = 'product',
    ProductAssign = 'productassign',
    Tickets = 'tickets',
    Voucher = 'voucher',
    WorkAllocation = 'work-allocation',
    Estimate = 'estimate',
    Attendance = 'attendance',
    RequestRaise = 'requests',
    Product_type = 'product-type',
    Invoice = 'invoice',
    Backend = 'backend',
    Services = 'services',
    Vehicle = 'vehicle',
    Sales = 'sales',
    Dispatch = 'dispatch'

}
